#lib defs
AVRLIB=/usr/lib/avr/include
LOCAL_INC=@top_srcdir@/include
STDDEFS=-DEXTRAM=$(EXTRAM) -DBAUD=9600 -DTIMERS=5 -D __SPIRAM__
CCFLAGS=
AM_LIBTOOLFLAGS=--silent

# -------------------------------------------------------
# Architectural defines
# -------------------------------------------------------
if AVR
CPU_TYPE=-mmcu=$(MCU)
STDDEFS+= -D__AVR__
CCFLAGS+= -ffreestanding -nostdinc -nostdlib
endif

# -------------------------------------------------------
# MCU specific
# -------------------------------------------------------
if ENABLE_ATMEGA328P
MCU=atmega328p
STDDEFS+= -DMEM=0x7FF
endif

if ENABLE_ATMEGA328
MCU=atmega328
STDDEFS+= -DMEM=0x7FF
endif

# -------------------------------------------------------
# Board specific
# -------------------------------------------------------
if ENABLE_UNO
F_CPU=16000000
STDDEFS+= -D__BOARD__ -D__ARDUINO__
else
F_CPU=8000000
endif

# -------------------------------------------------------
# Compile flags
# -------------------------------------------------------
CCFLAGS		+=-Wall -Os -I$(LOCAL_INC) \
		 -std=gnu89 $(CPU_TYPE) -D F_CPU=$(F_CPU) $(STDDEFS)
LD_FLAGS	= -r -Os -m avr5 -nostdlib
CPP_FLAGS	= -fno-exceptions -Os -Wall $(CPU_TYPE) -I$(LOCAL_INC) \
		   -DF_CPU=$(F_CPU) -ffunction-sections \
		  -fdata-sections -w $(STDDEFS)
ASFLAGS		= -mmcu=$(MCU) -I$(LOCAL_INC) -Wall
ARFLAGS		= rcsv

AM_CFLAGS=$(CCFLAGS)
AM_CCASFLAGS=$(ASFLAGS)
AM_CXXFLAGS=$(CPP_FLAGS)
AM_LDFLAGS=-Wl,-r,-mavr5
CP=cp

