#
# Makefile linux includer
#

MCU                     = atmega328p
F_CPU                   = 16000000
ARD_PORT                = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE    = 115200
AVRDUDE_ARD_PROGRAMMER  = arduino
AVRLIB                  = /usr/lib/avr/include
AVRBIN                  = /usr/bin
BIN			= /usr/bin
AVRDUDE_CONF            = -C /etc/avrdude.conf
